### ISSUE TITLE
IndexError when user add a layer to a 3Di schematisation editor layer group

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#257]
```
An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_schematisation_editor\__init__.py", line 128, in switch_workspace_context
    if active_layer.id() in self.model_layers_map[expected_layer_source]:
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_schematisation_editor\__init__.py", line 113, in model_layers_map
    connection_node_tree_layer = node.children()[0].children()[0]
IndexError: list index out of range


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.34.4-Prizren Prizren, decd43dc 
````

**Comment by leendertvanwolfswinkel** [comment]
Issue seems to be fixed
