### ISSUE TITLE
Missing connection node breaks import to geopackage

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#75]
If the spatialite contains a `v2_surface_map` or `v2_impervious_surface_map` with a `connection_node_id` that does not exist in `v2_connection_nodes`, an error is raised and the whole import process is broken.

Please change this to:
- Import/create all `surface_map` and `impervious_surface_map` features for which the referenced (impervious) surface map id's and referenced connection_node_ids are valid
- Skip features with invalid references and continue
- At the end of the import, warn the user that some (impervious) surface maps were not imported correctly, listing their id's and the reason for failure (missing connnection_node_id and/or missing (impervious) surface map id)

Example data can be found here: [https://app.zenhub.com/files/481141268/de49e8f0-3fed-4cef-ab93-6498493b163d/download](https://app.zenhub.com/files/481141268/de49e8f0-3fed-4cef-ab93-6498493b163d/download)

**Comment by leendertvanwolfswinkel** [comment]
Error is:

```

KeyError: 1303895 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_schematisation_editor\__init__.py", line 175, in load_from_spatialite
    converter.import_all_model_data()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_schematisation_editor\conversion.py", line 490, in import_all_model_data
    self.add_surface_map_geometries()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_schematisation_editor\conversion.py", line 296, in add_surface_map_geometries
    connection_node_geom = connection_node_points[node_id]
KeyError: 1303895
```

**Comment by leendertvanwolfswinkel** [comment]
Perfect
